spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://${CONFIG_SERVER_HOST:localhost}:8888"
  cloud:
    inetutils:
      ignored-interfaces:
        - "vEthernet.*"

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: ${EUREKA_INSTANCE_IP_ADDRESS:127.0.0.1}
